### ISSUE TITLE
Uncaught error in hot reloader setup

### ISSUE THREAD

**Issue by kastork** [capaj/jspm-react#6]
I did 

``` bash

npm i
npm start
```

Visit localhost:9080

```
localhost/:1 Uncaught (in promise) Error: Super expression must either be null or a function, not object
    Error loading http://localhost:9080/jspm_packages/github/capaj/systemjs-hot-reloader@0.5.1.js
    at exports.default (http://localhost:9080/jspm_packages/npm/babel-runtime@5.8.34/helpers/inherits.js:7:11)
    at http://localhost:9080/jspm_packages/github/capaj/systemjs-hot-reloader@0.5.1/hot-reloader.js!transpiled:35:9
    at execute (http://localhost:9080/jspm_packages/github/capaj/systemjs-hot-reloader@0.5.1/hot-reloader.js!transpiled:271:9)
    at u (http://localhost:9080/jspm_packages/system.js:5:2888)
    at u (http://localhost:9080/jspm_packages/system.js:5:2823)
    at Object.execute (http://localhost:9080/jspm_packages/system.js:5:5888)
    at y (http://localhost:9080/jspm_packages/system.js:4:10168)
    at x (http://localhost:9080/jspm_packages/system.js:4:10547)
    at p (http://localhost:9080/jspm_packages/system.js:4:8425)
    at h (http://localhost:9080/jspm_packages/system.js:4:8810)
```

My local node version is 5.4.1  npm is 3.3.12, jspm is  0.16.23

**Comment by capaj** [comment]
this is the same problem they had here: https://github.com/capaj/systemjs-hot-reloader/issues/42

This should just work. There has to be a bug in system.js. And I will find it, because this is getting ridiculous.

**Comment by josephfinlayson** [comment]
Also having this problem too. Hope it gets fixed!

**Comment by capaj** [comment]
@kastork @josephfinlayson should be fixed in 0.5.5 already-can you confirm?
Also make sure you use jspm 0.16.24 or jspm 0.17.0

**Comment by kastork** [comment]
Yup, seems to be working.  Had to update the hot-reloader package to 5.5,  and systemjs to 0.19.17

**Comment by jonahlau** [comment]
I am still getting this error. I've tried v0.5.5 of the hot-reloader package with jspm v0.17.0 and 0.16.24 

I'm only able to get it running with hot-reloader 0.5.5 with jspm 0.16.19.
